### ISSUE TITLE
v1 Checklist

### ISSUE THREAD

**Issue by Kacarott** [codewars/lambda-calculus#5]
List of TODOs before version one is ready:

kazk's checklist:
- [x] Create icon
- [x] Create codemirror mode
- [x]  Add docs "How to test"
- [x]  Add docs "How to compile and run"
- [x]  Add docs "How to set up environment"

Functionality checklist:
- [x] #6 
- [x] #8 
- [x] #12 
- [x] #13 
- [x] #14 
- [x] #19 
- [x] #25 
- [x] #26
- [x] #27
- [x] #21 
- [x] #28 

More to come...
